name "ey-elasticsearch"
description "Configuration & deployment of Elasticsearch on Engine Yard"
maintainer "Engine Yard"
maintainer_email "support@engineyard.com"
version "6.0.0"
issues_url "https://github.com/engineyard/ey-cookbooks-stable-v7/issues"
source_url "https://github.com/engineyard/ey-cookbooks-stable-v7"
