name "ey-base"
version "1.0.0"

depends "ey-ec2"
depends "ey-ephemeraldisk"
depends "ey-dynamic"
depends "ey-ruby"
depends "ey-ssh_keys"
depends "ey-cron"
depends "ey-env"
depends "ey-ntp"
depends "ey-env"
depends "ey-snapshot"
depends "ey-prompt"
