name "ey-memcached"
description "Configuration & deployment of Memcached on Engine Yard"
maintainer "Engine Yard"
maintainer_email "support@engineyard.com"
version "1.0.0"
issues_url "https://github.com/engineyard/ey-cookbooks-stable-v7/issues"
source_url "https://github.com/engineyard/ey-cookbooks-stable-v7"
