name "ey-core"
version "1.0.0"

depends "ey-lib"
depends "ey-sysctl"
depends "ey-instance-api"
depends "ey-sysctl"
depends "ey-syslog-ng"
depends "ey-timezones"
depends "ey-logrotate"
depends "ey-unattended-upgrades"
depends "ey-prechef"
