name "ey-app"
version "1.0.0"

depends "ey-deploy-keys"
depends "ey-app-logs"
# depends "unicorn"
# depends "passenger5"
depends "ey-puma"
# depends "monit"
depends "ey-env_vars"
# depends "cdn_distribution"
# depends "db_admin_tools"
# depends "mysql"
# depends "postgresql"
depends "ey-nginx"
# depends "ruby"
# depends "ey-db-libs"
depends "ey-haproxy"
# depends "php"