name "ey-app"
version "1.0.0"

depends "ey-deploy-keys"
depends "ey-app-logs"
depends "ey-unicorn"
# depends "passenger5"
depends "ey-puma"
depends "ey-puma_legacy"
# depends "monit"
depends "ey-env_vars"
# depends "cdn_distribution"
depends "ey-db_admin_tools"
depends "ey-mysql"
depends "ey-postgresql"
depends "ey-nginx"
# depends "ruby"
depends "ey-db-libs"
depends "ey-haproxy"
# depends "php"
